---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: nuvolaris-mongodb
  namespace: nuvolaris
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-scram
    - name: nuvolaris
      db: nuvolaris
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-nuvolaris-password
      roles:
        - name: userAdmin
          db: nuvolaris
      scramCredentialsSecretName: mongodb-nuvolaris-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
  namespace: nuvolaris
type: Opaque
stringData:
  password: sUpErs3cr3t
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-nuvolaris-password
  namespace: nuvolaris
type: Opaque
stringData:
  password: s3cr3t
