apiVersion: v1
kind: Pod
metadata:
  name: mongocli
  namespace: nuvolaris
spec:
  containers:
  - name: mongocli
    image: ghcr.io/nuvolaris/action-nodejs-v14:0.3.0-morpheus.22081008    
    env:
      - name: "MONGODB_URL" 
        value: "mongodb://nuvolaris:s3cr3t@nuvolaris-mongodb-0.nuvolaris-mongodb-svc/nuvolaris"
