# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: '3'

vars:
  KUBE:
    sh: ./detect.sh
  BASETAG: 0.2.0-trinity
  IMAGE: nuvolaris/nuvolaris-operator
  REPO: ghcr.io
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo nightly
  N: ""
  G: ""
  T: ""

env:
  OPERATOR_IMAGE:
    sh: awk -F= '/OPERATOR_IMAGE/ { print $2}' <Dockerfile
  OPERATOR_TAG:
    sh: awk -F= '/OPERATOR_TAG/ { print $2}' <Dockerfile
  CONTROLLER_IMAGE: 
    sh: awk -F= '/CONTROLLER_IMAGE/ { print $2}' <Dockerfile
  CONTROLLER_TAG: 
    sh:  awk -F= '/CONTROLLER_TAG/ { print $2}' <Dockerfile

dotenv:
  - .env

tasks:

  default: 
    - task: use

  setup:
    deps:
      - update-files-from-openwhisk
      - ssh-key
      - configure-env
    cmds:
      - poetry install
    status:
      - test -e $GOBIN/kopf

  env: env
  
  watch: watch kubectl -n nuvolaris get all
  
  cli: 
    - task: d:cli

  run:
    - task: d:run

  deploy: 
    - task: d:deploy

  destroy: 
    - task: d:destroy

  image-tag: git tag -d $(git tag) ; git tag -f {{.BASETAG}}.$(date +%y%m%d%H) ; git tag

  build: docker build . -t {{.REPO}}/{{.IMAGE}}:{{.TAG}} {{.CLI_ARGS}}

  buildx-and-push:
    - docker buildx build --platform linux/amd64,linux/arm64 -t {{.REPO}}/{{.IMAGE}}:{{.TAG}} . --push

  # configure env
  configure-env:
    cmds:
      - echo "please copy .env.dist in .env and add the keys"
    status:
      - test -f .env

  # update configuration files from openwhisk source
  update-files-from-openwhisk: 
    cmds:
      - | 
        if test -d ../nuvolaris-controller
        then cp -v ../nuvolaris-controller/openwhisk/ansible/files/*.json nuvolaris/files
        else echo "not found ../nuvolaris-controller/openwhisk"
        fi
    status:
      - test -f nuvolaris/files/runtimes.json

  # generate ssh keys
  ssh-key:
    cmds:
      - ssh-keygen -b 2048 -t rsa -f clusters/id_rsa -q -N ""
      - ssh-keygen  -y -f clusters/id_rsa >clusters/id_rsa.pub
    status:
      - test -f clusters/id_rsa.pub

  clean:
    cmds:
      - cmd: kubectl -n nuvolaris delete all --all
        ignore_error: true
      - cmd: kubectl -n nuvolaris delete wsk --all
        ignore_error: true
      - cmd: kubectl -n nuvolaris delete pvc --all
        ignore_error: true
      - cmd: kubectl -n nuvolaris delete ing --all
        ignore_error: true

  utest:
    cmds:
      - |
        for test in nuvolaris/{{.T}}*.py
        do  echo "*** [{{.KUBE}}] $test"
            poetry run python3 -m doctest $test {{.CLI_ARGS}}
        done
    silent: true

  itest: 
    cmds:
      - |
        kubectl apply -f deploy/nuvolaris-operator/whisk-crd.yaml
        kubectl apply -f deploy/nuvolaris-operator/nuvolaris-common.yaml
        for test in tests/{{.T}}*.ipy tests/{{.KUBE}}/{{.T}}*.ipy
        do  
            if test -e "$test"
            then  echo "*** [{{.KUBE}}] $test"
                  rm -f deploy/*/kustomization.yaml deploy/*/__*
                  poetry run ipython $test {{.CLI_ARGS}}
            fi
        done
    silent: true

  dtest:
    - task: test:all

  uitest:
    - task: clean
    - tast: utest
    - task: itest

  uidtest:
    - task: clean
    - task: utest
    - task: itest
    - task: dtest

  test: 
    - poetry run ipython profile create
    - cp test_profile.ipy ~/.ipython/profile_default/startup/
    - task: uitest

  all-kubes: 
    cmds: 
      - |-
        if test -z "{{.CLI_ARGS}}"
        then echo 'use "task all-kubes  -- <target> runs the target against all the available kubes'
        else  for cfg in clusters/*.kubeconfig
              do  cp -v $cfg ~/.kube/config
                  task {{.CLI_ARGS}}
              done
        fi
    silent: true

  use: 
    cmds:
    - |-
        if test -z "{{.N}}"
        then  echo "*** current: {{.KUBE}}"
              ls clusters/*.kubeconfig | sort | awk '{ print NR, $0 }'
              echo "*** select with 'task #'"
        else  CFG="$(ls -1 clusters/*.kubeconfig | tail +{{.N}} | head -1)" 
              cp $CFG ~/.kube/config
              echo "cluster: $(./detect.sh)"
              kubectl get nodes
        fi
    silent: true

  1: task use N=1
  2: task use N=2
  3: task use N=3
  4: task use N=4
  5: task use N=5
  6: task use N=6
  7: task use N=7
  8: task use N=8
  9: task use N=9

includes:
  d: 
    taskfile: TaskfileDev.yml
  t: 
    taskfile: TaskfileTest.yml
  kind:  
    taskfile: "clusters/kind.yml"
    dir: "clusters"
    optional: yes
  eks:
    taskfile: clusters/eks.yml
    dir: "clusters"
    optional: yes
  lks:  
    taskfile: clusters/lks.yml
    dir: clusters/
    optional: yes
