# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: '3'

vars:
  BASETAG: 0.2.0-trinity
  IMAGE: nuvolaris/nuvolaris-operator
  REPO: ghcr.io
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest
  CONTROLLER:
    sh: cat deploy/openwhisk-standalone/standalone-deploy.yaml | awk '/image:/ { print $2 }'
  OPERATOR: "{{.REPO}}/{{.IMAGE}}:{{.TAG}}"

dotenv:
  - .env

tasks:
  setup:
    deps:
      - update-files-from-openwhisk
      - ssh-key
      - configure-env
    cmds:
      - poetry install
    status:
      - test -e $GOBIN/kopf

  env: env
  watchpo: watch kubectl -n nuvolaris get po
  
  # configure env
  configure-env:
    cmds:
      - echo "please copy .env.dist in .env and add the keys"
    status:
      - test -f .env

  # update configuration files from openwhisk source
  update-files-from-openwhisk: 
    cmds:
      - | 
        if test -d ../nuvolaris-controller
        then cp -v ../nuvolaris-controller/openwhisk/ansible/files/*.json nuvolaris/files
        else echo "not found ../nuvolaris-controller/openwhisk"
        fi
    status:
      - test -f nuvolaris/files/runtimes.json

  # generate ssh keys
  ssh-key:
    cmds:
      - ssh-keygen -b 2048 -t rsa -f clusters/id_rsa -q -N ""
      - ssh-keygen  -y -f clusters/id_rsa >clusters/id_rsa.pub
    status:
      - test -f clusters/id_rsa.pub

  image-tag: git tag -d $(git tag) ; git tag -f {{.BASETAG}}.$(date +%y%m%d%H) ; git tag

  build: docker build . -t {{.REPO}}/{{.IMAGE}}:{{.TAG}} {{.CLI_ARGS}}
  
  buildx-and-push:
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{.REPO}}/{{.IMAGE}}:{{.TAG}} . --push

  unit: |
    for test in nuvolaris/{{.T}}*.py
    do  echo "*** $test"
        poetry run python3 -m doctest $test {{.CLI_ARGS}}
    done

  integ: |
    for test in tests/{{.T}}*.ipy
    do  echo "*** $test"
        poetry run ipython $test {{.CLI_ARGS}}
    done

  test:
    - task: unit
    - task: integ
    - task: test:all

includes:
  dev: TaskfileDev.yml
  test: 
    taskfile: TaskfileTest.yml
    vars:
      CONTROLLER: "{{.CONTROLLER}}"
      OPERATOR: "{{.OPERATOR}}"
  kind:  
    taskfile: "../nuvolaris-testing/public/clusters/kind.yml"
    dir: "../nuvolaris-testing/public/clusters"
    optional: yes
  eks:
    taskfile: ../nuvolaris-testing/public/clusters/eks.yml
    dir: "../nuvolaris-testing/public/clusters"
    optional: yes
  lks:  
    taskfile: ../nuvolaris-testing/public/clusters/lks.yml
    dir: ../nuvolaris-testing/public/clusters/
    optional: yes
