apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: nuvolaris-kafka
spec:
  serviceName: nuvolaris-kafka
  replicas: 1
  selector:
    matchLabels:
      app: nuvolaris-kafka
  template:
    metadata:
      labels:
        app: nuvolaris-kafka
    spec:
#      volumes:
#        - name: kafka-storage
#          persistentVolumeClaim:
#            claimName: kafka-pv-claim
      containers:
        - name: kafka-container
          image: bashj79/kafka-kraft
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: kafka-ssl
          env:
            - name: REPLICAS
              value: '1'
            - name: SERVICE
              value: nuvolaris-kafka
            - name: NAMESPACE
              value: default
#            - name: SHARE_DIR
#              value: /mnt/kafka
#          volumeMounts:
#            - name: kafka-storage
#              mountPath: /mnt/kafka

