---
apiVersion: v1
kind: Namespace
metadata:
  name: nuvolaris
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nuvolaris-operator
  namespace: nuvolaris
  labels:
    app: nuvolaris-operator
