apiVersion: v1
kind: Secret
metadata:
  name: postgres-nuvolaris-secret
  namespace: nuvolaris
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  nuvolarisUserPassword: gfjsgfksjdsfjasgfjkagfksgjhagjkjkhsj