apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: whisks.nuvolaris.org
  namespace: nuvolaris
spec:
  scope: Namespaced
  group: nuvolaris.org
  names:
    kind: Whisk
    plural: whisks
    singular: whisk
    shortNames:
      - wsk
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } } 
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                debug:
                  type: boolean
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Debug
          type: string
          priority: 0
          jsonPath: .spec.debug
          description: Debugging enabled
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.whick_create.message
          description: As returned from the handler (sometimes).

